name: Auto Run Batch Script

on:
  schedule:
    - cron: '0 10,12,14,16,18,20,22 * * *'  # JST 19時〜翌5時の1日7回
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas requests gspread oauth2client beautifulsoup4

      - name: Set up Google Credentials
        run: echo "$GOOGLE_CREDS_JSON" | base64 --decode > service_account.json
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

      - name: Run batch script
        run: python batch_main.py
